### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jpfairbanks**
update `Sys.DL_LOAD_PATH` to `Libdl.DL_LOAD_PATH`

### CODE REVIEW

**Comment by jpfairbanks** [comment]
The line "Inserting this command into your `.juliarc.jl` file will cause this to
 happen automatically each time you start Julia." implies that this is necessary for the library to work. Is that true?

**Comment by ggggggggg** [comment]
In the case where `using HDF5` doesn't work because it can't find the library, and adding something to `DL_LOAD_PATH` helps, putting that in the `.juliarc.jl` file would be convenient.  I used to use this workaround, but no longer need to, probably thanks to `Homebrew.jl`.

**Comment by timholy** [comment]
On julia 0.3 it's still `Sys` unless you're `using Compat`. Can you modify this to acknowledge that fact?

**Comment by timholy** [comment]
At this point 0.3 is pretty old so let's just go with it.

**Pull request merged**
