### PR TITLE
Enable collecting coverage statistics

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by timholy** [comment]
LGTM.

**Comment by tkelman** [comment]
Could also just delete the entire `script` section since it's identical to the default.

**Comment by eschnett** [comment]
Where do I see the default?

**Comment by tkelman** [comment]
https://docs.travis-ci.com/user/languages/julia#Default-Test-Script, or how it's constructed here https://github.com/travis-ci/travis-build/blob/3f8180a07357b712873b742b03683d42a9d0eb45/lib/travis/build/script/julia.rb#L63-L85, or the echo'd steps output from a travis run without manual setting of `script`.

**Comment by eschnett** [comment]
Script has been simplified.

**Pull request merged**
